# Generated by Django 4.2.25 on 2025-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('still_mind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
